version: "2"

services:
  cp:
    build:
      context: ""
      dockerfile: Dockerfile
    container_name: video-chat
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3002:3002"
    volumes:
      - ./.env:/home/node/app/.env